export enum PERMISSIONS {
  USER_CREATE = "USER_CREATE",
  USER_EDIT = "USER_EDIT",
  USER_GET = "USER_GET",
  USER_DELETE = "USER_DELETE",

  GROUP_CREATE = "GROUP_CREATE",
  GROUP_EDIT = "GROUP_EDIT",
  GROUP_GET = "GROUP_GET",
  GROUP_DELETE = "GROUP_DELETE",

    PERSON_CREATE = "PERSON_CREATE",
  PERSON_EDIT = "PERSON_EDIT",
  PERSON_GET = "PERSON_GET",
  PERSON_DELETE = "PERSON_DELETE",

  ENROLLMENT_CREATE = "ENROLLMENT_CREATE",
  ENROLLMENT_EDIT = "GROUP_EDIT",
  GROUP_GET = "ENROLLMENT_GET",
  ENROLLMENT_DELETE = "ENROLLMENT_DELETE",


  GRADE_CREATE = "GRADE_CREATE",
  GRADE_EDIT = "GRADE_EDIT",
  GRADE_GET = "GRADE_GET",
  GRADE_DELETE = "GRADE_DELETE",

  SCHOOL_CREATE = "SCHOOL_CREATE",
  SCHOOL_EDIT = "SCHOOL_EDIT",
  SCHOOL_GET = "SCHOOL_GET",
  SCHOOL_DELETE = "SCHOOL_DELETE",

  TEACHER_CREATE = "TEACHER_CREATE",
  TEACHER_EDIT = "TEACHER_EDIT",
  TEACHER_GET = "TEACHER_GET",
  TEACHER_DELETE = "TEACHER_DELETE",

  STUDENT_CREATE = "STUDENT_CREATE",
  STUDENT_EDIT = "STUDENT_EDIT",
  STUDENT_GET = "STUDENT_GET",
  STUDENT_DELETE = "STUDENT_DELETE",

  SCHEDULE_CREATE = "SCHEDULE_CREATE",
  SCHEDULE_EDIT = "SCHEDULE_EDIT",
  SCHEDULE_GET = "SCHEDULE_GET",
  SCHEDULE_DELETE = "SCHEDULE_DELETE",

  SUBJECT_CREATE = "SUBJECT_CREATE",
  SUBJECT_EDIT = "SUBJECT_EDIT",
  SUBJECT_GET = "SUBJECT_GET",
  SUBJECT_DELETE = "SUBJECT_DELETE",

  EVENT_CREATE = "EVENT_CREATE",
  EVENT_EDIT = "EVENT_EDIT",
  EVENT_GET = "EVENT_GET",
  EVENT_DELETE = "EVENT_DELETE",

  PARENT_CREATE = "PARENT_CREATE",
  PARENT_EDIT = "PARENT_EDIT",
  PARENT_GET = "PARENT_GET",
  PARENT_DELETE = "PARENT_DELETE",
}


export enum ROLES {
  USER = "USER",
  MOD = "MOD",
  ADMIN = "ADMIN",
  DIRECTIVE_ADMIN = "DIRECTIVE_ADMIN",
  PARENT = "PARENT",
}




export type Permission = {
  id: string;
  name: PERMISSIONS;
};

export type Role = {
  id: string;
  name: ROLES;
  permissions: Permission[];
};